formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.
# installations will go into the standard /tmp/am hierarchy

applications:
  builtinAppsManifestDir: ["${CONFIG_PWD}/apps", "${CONFIG_PWD}/examples"]
  installedAppsManifestDir: "/tmp/am/manifests"
  appImageMountDir: "/tmp/am/image-mounts"
  database: "/tmp/am/apps.db"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "${CONFIG_PWD}/imports/ui_config/default", "${CONFIG_PWD}/imports/shared" ]

# ... as well as the SystemUI

ui:
  fullscreen: no
  style: "${CONFIG_PWD}/styles/neptune"
  mainQml: "${CONFIG_PWD}/Main.qml"
  importPaths: [ "${CONFIG_PWD}/imports/ui_config/default", "${CONFIG_PWD}/imports/shared", "${CONFIG_PWD}/imports/system", "${CONFIG_PWD}/sysui" ]
  windowIcon: "${CONFIG_PWD}/imports/assets/icons/active/apps@96.png"

systemProperties:
    public:
      showCluster: yes
    private:
      appStoreServerUrl: 'http://chaos.pelagicore.net:8080'

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

# simulate an internal and a SD-card installation location

installationLocations:
- id: "internal-0"
  installationPath: "/tmp/am/apps"
  documentPath: "/tmp/am/docs"
  mountPoint: "/tmp"
  isDefault: true

# useful debug wrappers - mainly for Unix
# %program% and %arguments% are internal variables

debugWrappers:
- name: gdbserver
  command: [ '/usr/bin/gdbserver', ':%port%', '%program%', '%arguments%' ]
  parameters:  # <name>: <default value>
    port: 5555
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
- name: qmldebugger # can also be used for the qmlprofiler
  command: ['%program%', '-qmljsdebugger=port:%port%,block', '--qml-debug', '%arguments%' ]
  parameters:  # <name>: <default value>
    port: 3456
  supportedRuntimes: [ qml ]
  supportedContainers: [ process ]
- name: cppqmldebugger
  command: [ '/usr/bin/gdbserver', ':%gdbport%', '%program%', '-qmljsdebugger=port:%qmlport%,block', '--qml-debug', '%arguments%' ]
  parameters:  # <name>: <default value>
    gdbport: 5555
    qmlport: 3456
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
- name: valgrind
  command: [ '/usr/bin/valgrind', '%program%', '%arguments%' ]
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
- name: strace
  command: [ '/usr/bin/strace', '%program%', '%arguments%' ]
  supportedRuntimes: [ native, qml ]
  supportedContainers: [ process ]
